#!/bin/bash
#El valor de registry debo cambiarlo, puesto que no tendo ip fija en esa instancia
export REGISTRY="ec2-3-250-155-176.eu-west-1.compute.amazonaws.com:5000"
export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
#export PASS=$(sed -n '3p' /tmp/.auth)

#docker login -u ricardoandre97 -p $PASS
cd /home/ubuntu/jenkins/ && docker-compose up -d
